-- liquibase formatted sql

-- changeset salimgareeva:1
CREATE schema IF NOT EXISTS categories;
create table if not exists categories
(
    id            BIGINT generated by default as identity primary key,
    name         TEXT             NOT NULL
);

CREATE schema IF NOT EXISTS feeds;
create table if not exists feeds
(
    id            BIGINT generated by default as identity primary key,
    name         TEXT             NOT NULL,
    content       TEXT             NOT NULL,
    data_publication TIMESTAMP             NOT NULL,
     category_id BIGINT NOT NULL REFERENCES categories (id)
--     category BIGINT NOT NULL REFERENCES categories (id)
);
